/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.FilmeController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Filme;
import view.TelaCadastroFilme;

/**
 *
 * @author ceceb
 */
public class TelaConsultaFilme extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaFilme
     */
    public TelaConsultaFilme() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultaFilme = new javax.swing.JPanel();
        jLabelTituloFilme = new javax.swing.JLabel();
        jTextFieldTituloFilme = new javax.swing.JTextField();
        jButtonConsultarFilme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultaFilme = new javax.swing.JTable();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Video Locadora");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fecharJanela(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelConsultaFilme.setBackground(new java.awt.Color(0, 255, 255));

        jLabelTituloFilme.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloFilme.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloFilme.setText("Título do Filme:");
        jLabelTituloFilme.setToolTipText("");

        jTextFieldTituloFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonConsultarFilme.setBackground(new java.awt.Color(204, 204, 204));
        jButtonConsultarFilme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConsultarFilme.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConsultarFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/lupa.png"))); // NOI18N
        jButtonConsultarFilme.setPreferredSize(new java.awt.Dimension(46, 46));
        jButtonConsultarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarFilmeActionPerformed(evt);
            }
        });

        jTableConsultaFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Gênero", "Sinopse", "Duração"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableConsultaFilme);

        javax.swing.GroupLayout jPanelConsultaFilmeLayout = new javax.swing.GroupLayout(jPanelConsultaFilme);
        jPanelConsultaFilme.setLayout(jPanelConsultaFilmeLayout);
        jPanelConsultaFilmeLayout.setHorizontalGroup(
            jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                        .addComponent(jLabelTituloFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanelConsultaFilmeLayout.setVerticalGroup(
            jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                .addGroup(jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloFilme)
                            .addComponent(jTextFieldTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonConsultarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon.png"))); // NOI18N
        jLabelTitulo.setText("Consulta de Filme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConsultaFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanelConsultaFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharJanela
       
    }//GEN-LAST:event_fecharJanela

    private void jButtonConsultarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarFilmeActionPerformed
        String titulo = jTextFieldTituloFilme.getText();
        if(titulo != null && titulo.length() > 0){
        String[] colunas = {"Código", "Título", "Gênero", "Sinopse", "Duração"};
        DefaultTableModel model = new DefaultTableModel(colunas, 0){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        };
        jTableConsultaFilme.setModel(model);
        model.setRowCount(0);
        try{
            FilmeController filmeController = new FilmeController();
            ArrayList<Filme> filmes = filmeController.listarFilmes(titulo);
            filmes.forEach((Filme filme) -> {
                model.addRow(new Object[] {
                    filme.getCodFilme(),
                    filme.getTitulo(),
                    filme.getGenero(),
                    filme.getSinopse(),
                    filme.getDuracao()});
            });
        }catch(Exception e){
            e.printStackTrace();
        }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Título do Filme'");
            String[] colunas = {"Código", "Título", "Gênero", "Sinopse", "Duração"};
            DefaultTableModel model1 = new DefaultTableModel(colunas, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            };
            jTableConsultaFilme.setModel(model1);
            try{
            FilmeController c = new FilmeController();
            ArrayList<Filme> todosFilmes = c.listarTodosFilmes();
            todosFilmes.forEach((Filme filme) -> {
                    model1.addRow(new Object[] {
                        filme.getCodFilme(),
                        filme.getTitulo(),
                        filme.getGenero(),
                        filme.getSinopse(),
                        filme.getDuracao()});
                });
            }catch(Exception e){
                e.printStackTrace();
            }
        }    
    }//GEN-LAST:event_jButtonConsultarFilmeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String[] colunas = {"Código", "Título", "Gênero", "Sinopse", "Duração"};
        DefaultTableModel model2 = new DefaultTableModel(colunas, 0){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        };
        jTableConsultaFilme.setModel(model2);
        try{
        FilmeController c = new FilmeController();
        ArrayList<Filme> todosFilmes = c.listarTodosFilmes();
        todosFilmes.forEach((Filme filme) -> {
                model2.addRow(new Object[] {
                    filme.getCodFilme(),
                    filme.getTitulo(),
                    filme.getGenero(),
                    filme.getSinopse(),
                    filme.getDuracao()});
            });
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarFilme;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloFilme;
    private javax.swing.JPanel jPanelConsultaFilme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultaFilme;
    private javax.swing.JTextField jTextFieldTituloFilme;
    // End of variables declaration//GEN-END:variables
}
