/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ClienteController;
import Controller.FilmeController;
import Controller.ItemController;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Filme;

/**
 *
 * @author ceceb
 */
public class TelaCadastroItem extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroItem
     */
    public TelaCadastroItem() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLocacaoFilme = new javax.swing.JLabel();
        jPanelCadastroFilme = new javax.swing.JPanel();
        jLabelCodigoFilme = new javax.swing.JLabel();
        jButtonConsultarCodCliente = new javax.swing.JButton();
        jLabelPreco = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelTitulo2 = new javax.swing.JLabel();
        jButtonSalvarLocacao = new javax.swing.JButton();
        jButtonLimpar1 = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        jButtonConsultar1 = new javax.swing.JButton();
        jTextFieldTituloFilme = new javax.swing.JTextField();
        jLabelCodigoFilme1 = new javax.swing.JLabel();
        jFormattedTextFieldCodigoCliente = new javax.swing.JFormattedTextField();
        jLabelCodigoCliente = new javax.swing.JLabel();
        jFormattedTextFieldCodigoFilme = new javax.swing.JFormattedTextField();
        jButtonConsultarCodFilme1 = new javax.swing.JButton();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldTituloCPF = new javax.swing.JTextField();
        jButtonOKFilme = new javax.swing.JButton();
        jButtonOKCliente = new javax.swing.JButton();
        jFormattedTextFieldPreco = new javax.swing.JFormattedTextField();
        jLabelPreco1 = new javax.swing.JLabel();
        jFormattedTextFieldDataLocacao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Video Locadora");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelLocacaoFilme.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelLocacaoFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon.png"))); // NOI18N
        jLabelLocacaoFilme.setText("Locação de Filme");

        jPanelCadastroFilme.setBackground(new java.awt.Color(0, 255, 255));
        jPanelCadastroFilme.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelCodigoFilme.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelCodigoFilme.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigoFilme.setText("Código Filme:");
        jLabelCodigoFilme.setToolTipText("");

        jButtonConsultarCodCliente.setBackground(new java.awt.Color(204, 204, 204));
        jButtonConsultarCodCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConsultarCodCliente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConsultarCodCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/lupa.png"))); // NOI18N
        jButtonConsultarCodCliente.setToolTipText("Consulte aqui o código do filme");
        jButtonConsultarCodCliente.setPreferredSize(new java.awt.Dimension(46, 46));
        jButtonConsultarCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarCodClienteActionPerformed(evt);
            }
        });

        jLabelPreco.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPreco.setText("Preço:");
        jLabelPreco.setToolTipText("");

        jComboBoxTipo.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um tipo", "Blu-Ray Disc", "CD", "DVD" }));

        jLabelTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo2.setText("Tipo:");
        jLabelTitulo2.setToolTipText("");

        jButtonSalvarLocacao.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalvarLocacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSalvarLocacao.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarLocacao.setText("Salvar Locação");
        jButtonSalvarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarLocacaoActionPerformed(evt);
            }
        });

        jButtonLimpar1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonLimpar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLimpar1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimpar1.setText("Limpar");
        jButtonLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpar1ActionPerformed(evt);
            }
        });

        jButtonCancelar1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCancelar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancelar1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar1.setText("Cancelar");
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });

        jButtonConsultar1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonConsultar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConsultar1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConsultar1.setText("Consultar Locações");
        jButtonConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultar1ActionPerformed(evt);
            }
        });

        jTextFieldTituloFilme.setEditable(false);
        jTextFieldTituloFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTituloFilme.setToolTipText("Título do filme selecionado");
        jTextFieldTituloFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloFilmeActionPerformed(evt);
            }
        });

        jLabelCodigoFilme1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelCodigoFilme1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigoFilme1.setText("Título do Filme:");
        jLabelCodigoFilme1.setToolTipText("");

        jFormattedTextFieldCodigoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldCodigoCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jFormattedTextFieldCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCodigoClienteActionPerformed(evt);
            }
        });

        jLabelCodigoCliente.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelCodigoCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigoCliente.setText("Código Cliente:");
        jLabelCodigoCliente.setToolTipText("");

        jFormattedTextFieldCodigoFilme.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldCodigoFilme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonConsultarCodFilme1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonConsultarCodFilme1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConsultarCodFilme1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConsultarCodFilme1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/lupa.png"))); // NOI18N
        jButtonConsultarCodFilme1.setToolTipText("Consulte aqui o código do filme");
        jButtonConsultarCodFilme1.setPreferredSize(new java.awt.Dimension(46, 46));
        jButtonConsultarCodFilme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarCodFilme1ActionPerformed(evt);
            }
        });

        jLabelCPF.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCPF.setText("CPF:");
        jLabelCPF.setToolTipText("");

        jTextFieldTituloCPF.setEditable(false);
        jTextFieldTituloCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTituloCPF.setToolTipText("CPF do Locador selecionado");
        jTextFieldTituloCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloCPFActionPerformed(evt);
            }
        });

        jButtonOKFilme.setText("OK");
        jButtonOKFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKFilmeActionPerformed(evt);
            }
        });

        jButtonOKCliente.setText("OK");
        jButtonOKCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKClienteActionPerformed(evt);
            }
        });

        jFormattedTextFieldPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelPreco1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelPreco1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPreco1.setText("Data da Locação:");
        jLabelPreco1.setToolTipText("");

        try {
            jFormattedTextFieldDataLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataLocacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelCadastroFilmeLayout = new javax.swing.GroupLayout(jPanelCadastroFilme);
        jPanelCadastroFilme.setLayout(jPanelCadastroFilmeLayout);
        jPanelCadastroFilmeLayout.setHorizontalGroup(
            jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFilmeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroFilmeLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabelCodigoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOKCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultarCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroFilmeLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastroFilmeLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelCodigoFilme)
                                    .addComponent(jLabelCodigoFilme1)
                                    .addComponent(jLabelCPF)
                                    .addComponent(jLabelTitulo2)
                                    .addComponent(jLabelPreco)
                                    .addComponent(jLabelPreco1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelCadastroFilmeLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldCodigoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOKFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonConsultarCodFilme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelCadastroFilmeLayout.createSequentialGroup()
                                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(283, 283, 283))
                                        .addComponent(jTextFieldTituloCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jFormattedTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCadastroFilmeLayout.createSequentialGroup()
                                .addComponent(jButtonSalvarLocacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonLimpar1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConsultar1)))
                        .addContainerGap(80, Short.MAX_VALUE))))
        );
        jPanelCadastroFilmeLayout.setVerticalGroup(
            jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFilmeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodigoFilme)
                        .addComponent(jFormattedTextFieldCodigoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOKFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonConsultarCodFilme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoFilme1)
                    .addComponent(jTextFieldTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConsultarCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodigoCliente)
                        .addComponent(jFormattedTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOKCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jTextFieldTituloCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo2)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreco)
                    .addComponent(jFormattedTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreco1)
                    .addComponent(jFormattedTextFieldDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelCadastroFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarLocacao)
                    .addComponent(jButtonLimpar1)
                    .addComponent(jButtonCancelar1)
                    .addComponent(jButtonConsultar1))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroFilme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLocacaoFilme)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelLocacaoFilme)
                .addGap(18, 18, 18)
                .addComponent(jPanelCadastroFilme, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarCodFilme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarCodFilme1ActionPerformed
        new TelaConsultaFilme().setVisible(true);
    }//GEN-LAST:event_jButtonConsultarCodFilme1ActionPerformed

    private void jButtonConsultarCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarCodClienteActionPerformed
        new TelaConsultaCliente().setVisible(true);
    }//GEN-LAST:event_jButtonConsultarCodClienteActionPerformed

    private void jTextFieldTituloFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloFilmeActionPerformed
           
    }//GEN-LAST:event_jTextFieldTituloFilmeActionPerformed

    private void jButtonOKFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKFilmeActionPerformed
        String codigo1 = jFormattedTextFieldCodigoFilme.getText();
        if(codigo1 != null && codigo1.length() > 0){
        try {
            Integer codigo = Integer.parseInt(jFormattedTextFieldCodigoFilme.getText());
            FilmeController c = new FilmeController();
            Filme filme = c.obterFilmePorCodigo(codigo);
            
            if(filme != null){
            String titulo = filme.getTitulo();
            jTextFieldTituloFilme.setText(titulo);
            }
            else{
                JOptionPane.showMessageDialog(null, "Selecione um código de filme válido.");
            }
        } catch (NumberFormatException e) {
            System.out.println("Erro ao converter código: " + e.getMessage());
        }
        }
        else{
                JOptionPane.showMessageDialog(null, "Selecione um código de filme válido.");
        }
    }//GEN-LAST:event_jButtonOKFilmeActionPerformed
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                  
    }//GEN-LAST:event_formWindowOpened

    private void jButtonOKClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKClienteActionPerformed
        String codigo2 = jFormattedTextFieldCodigoCliente.getText();
        if(codigo2 != null && codigo2.length() > 0){
        try {            
            Integer codigo = Integer.parseInt(jFormattedTextFieldCodigoCliente.getText());
            ClienteController c = new ClienteController();
            Cliente cliente = c.obterCPFPorCodigo(codigo);
            
            if(cliente != null){
            String cpf = cliente.getCpf();
            jTextFieldTituloCPF.setText(cpf);
            }
            else{
                JOptionPane.showMessageDialog(null, "Selecione um código de cliente válido.");
            }
        } catch (NumberFormatException e) {
            System.out.println("Erro ao converter código: " + e.getMessage());
        }
        }
        else{
                JOptionPane.showMessageDialog(null, "Selecione um código de cliente válido.");
        }
    }//GEN-LAST:event_jButtonOKClienteActionPerformed

    private void jFormattedTextFieldCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCodigoClienteActionPerformed

    private void jTextFieldTituloCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloCPFActionPerformed

    private void jButtonConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultar1ActionPerformed
        TelaConsultaItem tela = new TelaConsultaItem();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonConsultar1ActionPerformed

    private void jButtonSalvarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarLocacaoActionPerformed
        String codFilmeStr = jFormattedTextFieldCodigoFilme.getText();
        String codClienteStr = jFormattedTextFieldCodigoCliente.getText();
        String preco1 = jFormattedTextFieldPreco.getText();
        String tipo = jComboBoxTipo.getSelectedItem().toString();
        String dataLocacao = jFormattedTextFieldDataLocacao.getText();

        if (codFilmeStr.isEmpty() || codClienteStr.isEmpty() || preco1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente."); //adicionando uma caixa de diálogo caso os campos não estejam preenchidos corretamente
            return;
        }
        int codFilme = Integer.parseInt(codFilmeStr);
        int codCliente = Integer.parseInt(codClienteStr);
        preco1 = preco1.replace(",", "."); // substitui a vírgula pelo ponto
        double preco = Double.parseDouble(preco1);
        try {
            ItemController c = new ItemController();
            FilmeController c1 = new FilmeController();
            Filme filme = c1.obterFilmePorCodigo(codFilme);
            ClienteController c2 = new ClienteController();
            Cliente cliente = c2.obterCPFPorCodigo(codCliente);
            if (filme != null && cliente != null) {
                boolean deubom = c.cadastrarItem(codFilme, codCliente, preco, tipo, dataLocacao);
                if (deubom == true && jComboBoxTipo.getSelectedIndex() != 0) {
                    JOptionPane.showMessageDialog(null, "O cadastro deu certo."); // adicionando uma caixa de diálogo caso o meu controller pegue as informações necessárias
                    this.jButtonLimpar1ActionPerformed(evt); // puxando a minha função de limpar os campos automaticamente assim que o salvamento der certo
                } else {
                    JOptionPane.showMessageDialog(null, "Preencha os campos corretamente."); //adicionando uma caixa de diálogo caso os campos não estejam preenchidos corretamente
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um código de filme e/ou de cliente válido.");
            }            
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarLocacaoActionPerformed

    private void jButtonLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpar1ActionPerformed
        jFormattedTextFieldCodigoFilme.setText("");
        jTextFieldTituloFilme.setText("");
        jFormattedTextFieldCodigoCliente.setText("");
        jTextFieldTituloCPF.setText("");
        jComboBoxTipo.setSelectedIndex(0);
        jFormattedTextFieldPreco.setText("");
        jFormattedTextFieldDataLocacao.setText("");
    }//GEN-LAST:event_jButtonLimpar1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        this.dispose();        
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonConsultar1;
    private javax.swing.JButton jButtonConsultarCodCliente;
    private javax.swing.JButton jButtonConsultarCodFilme1;
    private javax.swing.JButton jButtonLimpar1;
    private javax.swing.JButton jButtonOKCliente;
    private javax.swing.JButton jButtonOKFilme;
    private javax.swing.JButton jButtonSalvarLocacao;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoFilme;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataLocacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldPreco;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCodigoCliente;
    private javax.swing.JLabel jLabelCodigoFilme;
    private javax.swing.JLabel jLabelCodigoFilme1;
    private javax.swing.JLabel jLabelLocacaoFilme;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelPreco1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanelCadastroFilme;
    private javax.swing.JTextField jTextFieldTituloCPF;
    private javax.swing.JTextField jTextFieldTituloFilme;
    // End of variables declaration//GEN-END:variables
}
