/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ItemController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Filme;
import model.Item;

/**
 *
 * @author ceceb
 */
public class TelaConsultaItem extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaItem
     */
    public TelaConsultaItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelConsultaFilme = new javax.swing.JPanel();
        jLabelTituloFilme = new javax.swing.JLabel();
        jTextFieldTituloFilme = new javax.swing.JTextField();
        jButtonConsultarItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultaItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon.png"))); // NOI18N
        jLabelTitulo.setText("Consulta de Locação");

        jPanelConsultaFilme.setBackground(new java.awt.Color(0, 255, 255));

        jLabelTituloFilme.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloFilme.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloFilme.setText("Título do Filme:");
        jLabelTituloFilme.setToolTipText("");

        jTextFieldTituloFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonConsultarItem.setBackground(new java.awt.Color(204, 204, 204));
        jButtonConsultarItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConsultarItem.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConsultarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/lupa.png"))); // NOI18N
        jButtonConsultarItem.setPreferredSize(new java.awt.Dimension(46, 46));
        jButtonConsultarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarItemActionPerformed(evt);
            }
        });

        jTableConsultaItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Preço", "Tipo", "Data de locação", "Título", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableConsultaItem);

        javax.swing.GroupLayout jPanelConsultaFilmeLayout = new javax.swing.GroupLayout(jPanelConsultaFilme);
        jPanelConsultaFilme.setLayout(jPanelConsultaFilmeLayout);
        jPanelConsultaFilmeLayout.setHorizontalGroup(
            jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabelTituloFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConsultarItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaFilmeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(21, 21, 21))
        );
        jPanelConsultaFilmeLayout.setVerticalGroup(
            jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                .addGroup(jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanelConsultaFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloFilme)
                            .addComponent(jTextFieldTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConsultaFilmeLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonConsultarItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConsultaFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanelConsultaFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarItemActionPerformed
        String titulo = jTextFieldTituloFilme.getText();
        if(titulo != null && titulo.length() > 0){
            String[] colunas = {"Código", "Preço", "Tipo", "Data de Locação", "Título", "CPF"};
            DefaultTableModel model = new DefaultTableModel(colunas, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            jTableConsultaItem.setModel(model);
            model.setRowCount(0);
            try{
                ItemController itemController = new ItemController();
                ArrayList<Item> itens = itemController.listarItens(titulo);
                itens.forEach(item -> {
                    Filme filme = item.getFilme();
                    Cliente cliente = item.getCliente();
                    model.addRow(new Object[]{
                        item.getCodItem(),
                        item.getPreco(),
                        item.getTipo(),
                        item.getDataLocacao(),
                        filme.getTitulo(),
                        cliente.getCpf()
                    });
                });
        }catch(Exception e){
            e.printStackTrace();
        }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Título do Filme'");
            String[] colunas = {"Código", "Preço", "Tipo", "Data de Locação", "Título", "CPF"};
            DefaultTableModel model1 = new DefaultTableModel(colunas, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            jTableConsultaItem.setModel(model1);
            try{
                ItemController itemController = new ItemController();
                ArrayList<Item> itens = itemController.listarTodosItens();
                itens.forEach(item -> {
                    Filme filme = item.getFilme();
                    Cliente cliente = item.getCliente();
                    model1.addRow(new Object[]{
                        item.getCodItem(),
                        item.getPreco(),
                        item.getTipo(),
                        item.getDataLocacao(),
                        filme.getTitulo(),
                        cliente.getCpf()
                    });
                });
        }catch(Exception e){
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButtonConsultarItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            String[] colunas = {"Código", "Preço", "Tipo", "Data de Locação", "Título", "CPF"};
            DefaultTableModel model1 = new DefaultTableModel(colunas, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            jTableConsultaItem.setModel(model1);
            try{
                ItemController itemController = new ItemController();
                ArrayList<Item> itens = itemController.listarTodosItens();
                itens.forEach(item -> {
                    Filme filme = item.getFilme();
                    Cliente cliente = item.getCliente();
                    model1.addRow(new Object[]{
                        item.getCodItem(),
                        item.getPreco(),
                        item.getTipo(),
                        item.getDataLocacao(),
                        filme.getTitulo(),
                        cliente.getCpf()
                    });
                });
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarItem;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloFilme;
    private javax.swing.JPanel jPanelConsultaFilme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultaItem;
    private javax.swing.JTextField jTextFieldTituloFilme;
    // End of variables declaration//GEN-END:variables
}
